theme = "dark_plus"

[editor]
line-number = "relative"
rulers = [81]

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
